import Head from 'next/head'
import Image from 'next/image'
import Intro from '../components/Intro.jsx' 
import Portfolio from '../components/Portfolio.jsx' 
import Timeline from '../components/Timeline.jsx' 
import Contact from '../components/Contact.jsx' 
import Footer from '../components/Footer.jsx' 

export default function Home() {
  return (
    <div>
      <Head>
        <title>Dat's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Intro />
      <Portfolio />
      <Timeline />
      <Contact/>
      <Footer/>

    </div>
  )
}
